service: flask-python-plagiarism
configValidationMode: error
provider:
  name: aws
  runtime: python3.7
  region: ap-south-1
  memorySize: 512
  timeout: 30
  # role: arn:aws:iam::035825521573:role/service-role/hu-evaluator-role-pue05nih
  tags:
    Org: HASHEDIN
    Product: PR001
    Dep: HU
  deploymentBucket:
    name: hu-evaluator
    serverSideEncryption: AES256
  deploymentPrefix: serverless
  stackName: pia-api
  stackTags:
    Org: HASHEDIN
    Product: PR001
    Dep: HU
package:
  patterns:
    - "!.serverless/**"
    - "!.serverless_plugins/**"
    - "!node_modules/**"
    - "!venv/**"
    - "!.idea/**"
    - "!.idea/**"
    - "!*.iml"
    - "!.git/**"
    - "!pyenv.cfg"
    - "!.gitignore"
    - "!README.md"
    - "!.github/**"
    - "!.__pycache__/**"
    - "!.logs/**"
    - "!.DS_Store"
    - "package.json"
    - "package-lock.json"

custom:
  Env: ${opt:stage, 'dev'}
  pythonRequirements:
    dockerizePip: false
  wsgi:
    app: main.app
    packageRequirements: false # this is to make wsgi not to pack ur dependencies since its handled by layers already

functions:
  app:
    handler: wsgi_handler.handler
    # layers:
    #   - arn:aws:lambda:ap-south-1:035825521573:layer:pia-flask:1

    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-python-requirements
  - serverless-wsgi
