service: flask-python-plagiarism

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  memorySize: 128
  role: arn:aws:iam::035825521573:role/service-role/hu-evaluator-role-pue05nih
  deploymentBucket:
    name: hu-evaluator
    serverSideEncryption: AES256
  deploymentPrefix: deployment
package:
  patterns:
    - "!.serverless/**"
    - "!.serverless_plugins/**"
    - "!node_modules/**"
    - "!venv/**"
    - "!.idea/**"
    - "!.idea/**"
    - "!*.iml"
    - "!.git/**"
    - "!pyenv.cfg"
    - "!.gitignore"
    - "!README.md"
    - "!.github/**"
    - "!.__pycache__/**"
    - "!.logs/**"
    - "!.DS_Store"

custom:
  Env: ${opt:stage, 'dev'}
  wsgi:
    app: main.app
    pythonRequirements:
      dockerizePip: true
      compatibleRuntimes:
        - python3.8
functions:
  app:
    handler: wsgi.handler
    layers:
      - arn:aws:lambda:ap-south-1:035825521573:layer:pia-flask:1
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-python-requirements
  - serverless-wsgi
