service: aws-connect-to-docDB

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-south-1
  memorySize: 128

custom:
  wsgi:
   app: main.app
   pythonRequirements:
    dockerizePip: true

functions:
  app:
   handler: wsgi.handler
   events:
    - http: ANY /
    - http: 'ANY {proxy+}'

plugins:
  - serverless-python-requirements
  - serverless-wsgi
